import { v4 as uuid } from 'uuid';
import { Email, type PlainEmail } from './email.js';

/**
 * create a single mock Email, supporting partial
 * overrides of any of its properties.
 */
export function mockEmail(overrides: Partial<PlainEmail> = {}): Email {
  const base: PlainEmail = {
    id: uuid(),
    gmailId: uuid(),
    threadId: uuid(),
    sender: 'Jane Doe',
    senderEmail: 'jane@example.com',
    subject: 'Hello there',
    body: 'Just checking in!',
    snippet: 'Just checking in!',
    summary: 'A quick check-in message.',
    category: 'work',
    importance: 4,
    needsReply: false,
    replyGenerated: false,
    bucket: 'fyi',
    receivedAt: new Date().toISOString(),
    read: false,
    archived: false,
  };

  return Email.from({ ...base, ...overrides });
}

/**
 * a rich mock set of ~15 emails mirroring the
 * inbox prototype, spanning every triage bucket.
 */
export function mockEmails(): Email[] {
  return [
    Email.from({
      id: 'e1',
      gmailId: 'gmail-e1',
      threadId: 'thread-e1',
      sender: 'John Carter',
      senderEmail: 'john@northwind.io',
      subject: 'Project update for Q3 rollout?',
      summary: 'Client is requesting a project update before the Thursday steering call.',
      body: 'Hi Peter,\n\nCould you share where we stand on the Q3 rollout? The steering committee meets Thursday and I would like to bring numbers.\n\nThanks,\nJohn',
      snippet: 'Could you share where we stand on the Q3 rollout?',
      category: 'work',
      importance: 9,
      needsReply: true,
      bucket: 'urgent',
      receivedAt: '2024-05-20T08:12:00.000Z',
      read: false,
      archived: false,
    }),
    Email.from({
      id: 'e2',
      gmailId: 'gmail-e2',
      threadId: 'thread-e2',
      sender: 'Revolut Security',
      senderEmail: 'no-reply@revolut.com',
      subject: 'Action required: verify your identity',
      summary: 'Your bank requires identity verification within 48 hours.',
      body: 'We need to confirm your identity to keep your account active. Please complete verification within 48 hours.',
      snippet: 'We need to confirm your identity to keep your account active.',
      category: 'bills',
      importance: 10,
      needsReply: false,
      bucket: 'urgent',
      receivedAt: '2024-05-20T07:45:00.000Z',
      read: false,
      archived: false,
    }),
    Email.from({
      id: 'e3',
      gmailId: 'gmail-e3',
      threadId: 'thread-e3',
      sender: 'Amazon',
      senderEmail: 'ship-confirm@amazon.com',
      subject: 'Your package has been delayed',
      summary: 'Delivery of your order moved from Tuesday to Friday.',
      body: 'Sorry — your package is delayed. New estimated delivery: Friday between 9am and 1pm.',
      snippet: 'Sorry — your package is delayed.',
      category: 'shopping',
      importance: 5,
      needsReply: false,
      bucket: 'fyi',
      receivedAt: '2024-05-20T07:02:00.000Z',
      read: false,
      archived: false,
    }),
    Email.from({
      id: 'e4',
      gmailId: 'gmail-e4',
      threadId: 'thread-e4',
      sender: 'Lena Fischer',
      senderEmail: 'lena@designstudio.de',
      subject: 'Contract review — one open point',
      summary: 'Legal flagged the liability clause and needs your decision.',
      body: 'Hi Peter,\n\nLegal is fine with everything except clause 7.2 on liability. Can you confirm the cap we agreed on?\n\nBest,\nLena',
      snippet: 'Legal is fine with everything except clause 7.2 on liability.',
      category: 'work',
      importance: 8,
      needsReply: true,
      bucket: 'needsReply',
      receivedAt: '2024-05-19T16:30:00.000Z',
      read: true,
      archived: false,
    }),
    Email.from({
      id: 'e5',
      gmailId: 'gmail-e5',
      threadId: 'thread-e5',
      sender: 'Mom',
      senderEmail: 'mom@family.net',
      subject: 'Sunday lunch?',
      summary: 'Family lunch invitation for Sunday at 1pm.',
      body: 'Are you coming Sunday? Grandma is making the good soup. Let me know before Friday!',
      snippet: 'Are you coming Sunday? Grandma is making the good soup.',
      category: 'family',
      importance: 6,
      needsReply: true,
      bucket: 'needsReply',
      receivedAt: '2024-05-19T12:15:00.000Z',
      read: true,
      archived: false,
    }),
    Email.from({
      id: 'e6',
      gmailId: 'gmail-e6',
      threadId: 'thread-e6',
      sender: 'Figma',
      senderEmail: 'news@figma.com',
      subject: 'What shipped this month in Figma',
      summary: 'Monthly product newsletter — no action needed.',
      body: 'Variables, new dev mode features, and more.',
      snippet: 'Variables, new dev mode features, and more.',
      category: 'marketing',
      importance: 1,
      needsReply: false,
      bucket: 'promotions',
      receivedAt: '2024-05-19T09:00:00.000Z',
      read: true,
      archived: false,
    }),
    Email.from({
      id: 'e7',
      gmailId: 'gmail-e7',
      threadId: 'thread-e7',
      sender: 'Notion',
      senderEmail: 'updates@notion.so',
      subject: 'New in Notion: AI meeting notes',
      summary: 'Product announcement newsletter.',
      body: 'Notion AI can now summarize your meetings automatically.',
      snippet: 'Notion AI can now summarize your meetings automatically.',
      category: 'marketing',
      importance: 1,
      needsReply: false,
      bucket: 'promotions',
      receivedAt: '2024-05-18T10:00:00.000Z',
      read: true,
      archived: false,
    }),
    Email.from({
      id: 'e8',
      gmailId: 'gmail-e8',
      threadId: 'thread-e8',
      sender: 'Spotify',
      senderEmail: 'news@spotify.com',
      subject: 'Your Weekly Discover playlist is ready',
      summary: 'Weekly music recommendations.',
      body: 'New tracks picked for you based on your listening history.',
      snippet: 'New tracks picked for you based on your listening history.',
      category: 'marketing',
      importance: 1,
      needsReply: false,
      bucket: 'promotions',
      receivedAt: '2024-05-18T08:00:00.000Z',
      read: true,
      archived: false,
    }),
    Email.from({
      id: 'e9',
      gmailId: 'gmail-e9',
      threadId: 'thread-e9',
      sender: 'Medium Daily Digest',
      senderEmail: 'noreply@medium.com',
      subject: 'Top stories for you today',
      summary: 'Curated reading list newsletter.',
      body: 'Handpicked stories based on your interests in design and tech.',
      snippet: 'Handpicked stories based on your interests in design and tech.',
      category: 'marketing',
      importance: 1,
      needsReply: false,
      bucket: 'promotions',
      receivedAt: '2024-05-17T09:30:00.000Z',
      read: true,
      archived: false,
    }),
    Email.from({
      id: 'e10',
      gmailId: 'gmail-e10',
      threadId: 'thread-e10',
      sender: 'City Water Utility',
      senderEmail: 'billing@citywater.gov',
      subject: 'Your monthly water bill is ready',
      summary: 'Monthly utility bill of $42.18 due June 1st.',
      body: 'Your water bill for this month is $42.18 and is due on June 1st. View your statement online.',
      snippet: 'Your water bill for this month is $42.18.',
      category: 'bills',
      importance: 4,
      needsReply: false,
      bucket: 'fyi',
      receivedAt: '2024-05-17T07:00:00.000Z',
      read: true,
      archived: false,
    }),
    Email.from({
      id: 'e11',
      gmailId: 'gmail-e11',
      threadId: 'thread-e11',
      sender: 'Sara Kim',
      senderEmail: 'sara.kim@northwind.io',
      subject: 'Design review moved to 3pm',
      summary: 'Meeting rescheduled from 2pm to 3pm today.',
      body: 'Hi, quick heads up — the design review moved to 3pm today. Same link.',
      snippet: 'Quick heads up — the design review moved to 3pm today.',
      category: 'work',
      importance: 6,
      needsReply: false,
      bucket: 'fyi',
      receivedAt: '2024-05-16T13:00:00.000Z',
      read: true,
      archived: false,
    }),
    Email.from({
      id: 'e12',
      gmailId: 'gmail-e12',
      threadId: 'thread-e12',
      sender: 'Zalando',
      senderEmail: 'deals@zalando.com',
      subject: 'Up to 40% off summer styles',
      summary: 'Seasonal promotional sale.',
      body: 'Shop the summer sale now with up to 40% off selected items.',
      snippet: 'Shop the summer sale now with up to 40% off.',
      category: 'shopping',
      importance: 2,
      needsReply: false,
      bucket: 'promotions',
      receivedAt: '2024-05-16T11:00:00.000Z',
      read: true,
      archived: false,
    }),
    Email.from({
      id: 'e13',
      gmailId: 'gmail-e13',
      threadId: 'thread-e13',
      sender: 'David Park',
      senderEmail: 'david@northwind.io',
      subject: 'Can you approve the invoice?',
      summary: 'Finance needs invoice approval before Friday payroll run.',
      body: 'Hi Peter, the vendor invoice for #4521 needs your approval before Friday. Can you take a look today?',
      snippet: 'The vendor invoice for #4521 needs your approval before Friday.',
      category: 'work',
      importance: 8,
      needsReply: true,
      bucket: 'needsReply',
      receivedAt: '2024-05-15T15:20:00.000Z',
      read: false,
      archived: false,
    }),
    Email.from({
      id: 'e14',
      gmailId: 'gmail-e14',
      threadId: 'thread-e14',
      sender: 'Dad',
      senderEmail: 'dad@family.net',
      subject: 'Happy birthday reminder',
      summary: 'Reminder about grandma birthday next week.',
      body: "Don't forget grandma's birthday is next Tuesday. Should we order flowers together?",
      snippet: "Don't forget grandma's birthday is next Tuesday.",
      category: 'family',
      importance: 3,
      needsReply: false,
      bucket: 'fyi',
      receivedAt: '2024-05-14T18:00:00.000Z',
      read: true,
      archived: false,
    }),
    Email.from({
      id: 'e15',
      gmailId: 'gmail-e15',
      threadId: 'thread-e15',
      sender: 'LinkedIn',
      senderEmail: 'notifications@linkedin.com',
      subject: 'You appeared in 12 searches this week',
      summary: 'Weekly profile activity summary.',
      body: 'Your profile appeared in 12 searches this week. See who is looking for someone like you.',
      snippet: 'Your profile appeared in 12 searches this week.',
      category: 'marketing',
      importance: 1,
      needsReply: false,
      bucket: 'promotions',
      receivedAt: '2024-05-14T09:00:00.000Z',
      read: true,
      archived: true,
    }),
  ];
}
